version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "faceIdAppKusu"
s3_bucket = "kususambuildrepo"
s3_prefix = "faceIdAppKusu"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

