version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "faceIdAppKusu"
s3_bucket = "codebucketkusu002"
s3_prefix = "faceIdAppKusu"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

